export const initialMockAccounts = [
  {
    id: "jyun",
    no: 1,
    empNo: "19784",
    dept: "디지털전략팀",
    position: "서기",
    name: "이지윤",
    password: "jyuntest",
  },
  {
    id: "hkim",
    no: 2,
    empNo: "20411",
    dept: "진료운영팀",
    position: "서기",
    name: "김하늘",
    password: "hkim1234",
  },
  {
    id: "mlee",
    no: 3,
    empNo: "21876",
    dept: "원무팀",
    position: "대리",
    name: "이민수",
    password: "mlee1234",
  },
  {
    id: "schoi",
    no: 4,
    empNo: "22315",
    dept: "간호부",
    position: "선임간호사",
    name: "최수진",
    password: "schoi1234",
  },
];